### ISSUE TITLE
[PE-D] No module timetable available

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-1/tp#225]
I think that given that most of the information about the module such as its description and workload distribution is available, the user would expect the module timetable to be available as well. However, it is not, which makes using the `timetable add` function very difficult to use as I have to use a different app (namely NUSMods) to find the lecture/tutorial/lab slots, then input them.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: astralum/ped#2

**Comment by saravanamani1999** [comment]
We did not extract the data for different timings for each lesson in a specific module as they are separated into individual json files for each module in the NUSMods api, as we wanted to be space efficient and stay within the memory space limits set we did not proceed with extracting this information. Also given that our product is expected to function without internet connection, we couldn't implement making a http request to nusmods api based on user input to retrieve these timings. Which is why the timings of lessons are not yet available as it's out of the current project's scope.
